### ISSUE TITLE
Error in generic rest function

### ISSUE THREAD

**Issue by oscartcy** [heroku/simple-salesforce#66]
Does anyone have an idea for the following error?

```python
Traceback (most recent call last):
  File "./tests/unit/run_apex_tests.py", line 272, in <module>
    counts = run_tests()
  File "./tests/unit/run_apex_tests.py", line 228, in run_tests
    result = sf.restful('runTestsSynchronous', params={'classnames': classname})
  File "/usr/lib/python2.7/site-packages/simple_salesforce/api.py", line 216, in restful
    if len(json_result) == 0:
TypeError: object of type 'NoneType' has no len()
```
and this is the call I made:

```python
result = sf.restful('runTestsSynchronous', params={'classnames': classname})
```
pip module versions with Python 2.7.5:
```
requests==2.7.0
simple-salesforce==0.67.2
```

**Comment by demianbrecht** [comment]
Hey @oscartcy, apologies for the horribly late response, but were you able to figure out the issue here?

**Comment by oscartcy** [comment]
Can't reproduce this issue any more after upgrading to 0.68.0. This issue can be close first I think =]

**Comment by demianbrecht** [comment]
Great, I'll close it for now but feel free to reopen if you run into it again.
